// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace clinik {
	
	
	public partial class patient_login {
		
		protected System.Web.UI.HtmlControls.HtmlForm patient_login_with_trace_code;
		
		protected System.Web.UI.WebControls.TextBox trace_code;
		
		protected System.Web.UI.WebControls.Button btn_trace_code;
		
		protected System.Web.UI.HtmlControls.HtmlForm patient_login_with_name_and_last_name;
		
		protected System.Web.UI.WebControls.TextBox name;
		
		protected System.Web.UI.WebControls.TextBox last_name;
		
		protected System.Web.UI.WebControls.TextBox mobile_number;
	}
}
