// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace clinik {
	
	
	public partial class patient_form {
		
		protected System.Web.UI.HtmlControls.HtmlForm patient_form_ppo;
		
		protected System.Web.UI.WebControls.TextBox name;
		
		protected System.Web.UI.WebControls.TextBox last_name;
		
		protected System.Web.UI.WebControls.TextBox personl_id;
		
		protected System.Web.UI.WebControls.DropDownList sex;
		
		protected System.Web.UI.WebControls.TextBox age;
		
		protected System.Web.UI.WebControls.TextBox height;
		
		protected System.Web.UI.WebControls.TextBox weigth;
		
		protected System.Web.UI.WebControls.TextBox mobile_phone_number;
		
		protected System.Web.UI.WebControls.TextBox email;
		
		protected System.Web.UI.WebControls.DropDownList cat_op_list;
		
		protected System.Web.UI.WebControls.DropDownList operation_kind;
		
		protected System.Web.UI.WebControls.DropDownList surgeon_name;
		
		protected System.Web.UI.WebControls.TextBox suggestion_operation_time_year;
		
		protected System.Web.UI.WebControls.TextBox suggestion_operation_time_month;
		
		protected System.Web.UI.WebControls.TextBox suggestion_operation_time_day;
		
		protected System.Web.UI.WebControls.DropDownList op_kind_patient;
		
		protected System.Web.UI.WebControls.TextBox op_date_patient_year;
		
		protected System.Web.UI.WebControls.TextBox op_date_patient_month;
		
		protected System.Web.UI.WebControls.TextBox op_date_patient_day;
		
		protected System.Web.UI.WebControls.DropDownList problem_during_op;
		
		protected System.Web.UI.WebControls.Button save_list_op;
		
		protected System.Web.UI.WebControls.DropDownList drugs_list;
		
		protected System.Web.UI.WebControls.TextBox drugs_explain;
		
		protected System.Web.UI.WebControls.Button save_list_drug_used;
		
		protected System.Web.UI.WebControls.CheckBox steroid_corti;
		
		protected System.Web.UI.WebControls.CheckBox smoker_addiction;
		
		protected System.Web.UI.WebControls.TextBox cigar_many;
		
		protected System.Web.UI.WebControls.TextBox year_use_smoke;
		
		protected System.Web.UI.WebControls.CheckBox smoker_now;
		
		protected System.Web.UI.WebControls.CheckBox alchol_use;
		
		protected System.Web.UI.WebControls.CheckBox drug_use;
		
		protected System.Web.UI.WebControls.CheckBox stair_up;
		
		protected System.Web.UI.WebControls.CheckBox heart_problem;
		
		protected System.Web.UI.WebControls.DropDownList heart_problem_list;
		
		protected System.Web.UI.WebControls.Button save_heart_problem_list;
		
		protected System.Web.UI.WebControls.Button submit;
		
		protected System.Web.UI.WebControls.DropDownList op_list_all;
		
		protected System.Web.UI.WebControls.DropDownList drugs_list_all;
	}
}
