// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace clinik {
	
	
	public partial class main {
		
		protected System.Web.UI.WebControls.Button btn_login_doctor;
		
		protected System.Web.UI.WebControls.Button register_patient_form;
		
		protected System.Web.UI.WebControls.Button btn_show_edit_patient_form;
	}
}
